### ISSUE TITLE
Build error on Linux using latest commit

### ISSUE THREAD

**Issue by thirstyfish** [Mowje/node-cryptopp#5]
Using the current master, my npm install fails at cryptopp on ubuntu server 14.04.1 LTS.
I had to make it work by editing the package.json to use a previous commit for cryptopp like so:
```
git+https://github.com/Mowje/node-cryptopp.git#b62060cd59e61c947104061c5db5daa1c54cf695
```

The error thrown when using the current master branch is the following:

```
⇒  npm install

> cryptopp@0.2.3 preinstall /home/ubuntu/Projects/server/node_modules/cryptopp
> make git-getcryptopp && make lib

rm -rf cryptopp
git clone https://github.com/Mowje/cryptopp.git
Cloning into 'cryptopp'...
remote: Counting objects: 386, done.
remote: Total 386 (delta 0), reused 0 (delta 0)
Receiving objects: 100% (386/386), 2.13 MiB | 338.00 KiB/s, done.
Resolving deltas: 100% (30/30), done.
Checking connectivity... done.
rm cryptopp/GNUmakefile
#cp compileLib cryptopp/GNUmakefile
node prepareBuild.js
Standard binding and compilation process

fs.js:432
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT, no such file or directory 'std-binding.gyp'
    at Object.fs.openSync (fs.js:432:18)
    at Object.fs.readFileSync (fs.js:286:15)
    at Object.<anonymous> (/home/ubuntu/Projects/server/node_modules/cryptopp/prepareBuild.js:21:37)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3
make: *** [lib] Error 8
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
```

**Comment by BatikhSouri** [comment]
Hey. Sorry for the late reply.

Can you still reproduce the bug? I tried to reproduce it on Debian 7 and Ubuntu Server 14.04 but with no success.

**Comment by BatikhSouri** [comment]
Closing it for now. Feel free to re-open it if the bug appears again

**Comment by BatikhSouri** [comment]
Hey @thirstyfish ! I haven't been able to reproduce the bug, but I've been able to fix it. Issue #6 is very similar to yours and I've been able to guess what the issue was and fix it. Please retry with the latest build and confirm. :)

**Comment by thirstyfish** [comment]
Unfortunately, I can't test on a Linux box atm, but I'm getting the same error message on OSX (Yosemite), but this time it fails on copying the osx13-binding.gyp.

I can still get your lib working with node v0.10 using the earlier commit I mentioned in this issue before, but the biggest issue for me is that it's not working at all on node v0.11 and up, due to an API change.
Would you consider using nan to be agnostic of the API changes as mentioned in this thread:
https://github.com/mscdex/mmmagic/issues/16

This is the error I get with node v0.11:

```
#define BUILDING_NODE_EXTENSION 1
        ^
In file included from ../node-cryptopp.cpp:18:
.././keyring.h:17:30: error: expected class name
class KeyRing : public node::ObjectWrap{
                             ^
.././keyring.h:64:41: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
        static v8::Handle<v8::Value> New(const v8::Arguments& args);
                                               ^~~~~~~~~~~~~
                                               v8::internal::Arguments
/Users/thirstyfish/.node-gyp/0.11.16/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../node-cryptopp.cpp:18:
.././keyring.h:65:45: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
        static v8::Handle<v8::Value> Decrypt(const v8::Arguments& args);
                                                   ^~~~~~~~~~~~~
                                                   v8::internal::Arguments
/Users/thirstyfish/.node-gyp/0.11.16/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../node-cryptopp.cpp:18:
.././keyring.h:66:42: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
        static v8::Handle<v8::Value> Sign(const v8::Arguments& args);
                                                ^~~~~~~~~~~~~
                                                v8::internal::Arguments
/Users/thirstyfish/.node-gyp/0.11.16/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../node-cryptopp.cpp:18:
.././keyring.h:67:43: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
        static v8::Handle<v8::Value> Agree(const v8::Arguments& args);
                                                 ^~~~~~~~~~~~~
                                                 v8::internal::Arguments
/Users/thirstyfish/.node-gyp/0.11.16/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../node-cryptopp.cpp:18:
.././keyring.h:68:51: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
        static v8::Handle<v8::Value> PublicKeyInfo(const v8::Arguments& args);
                                                         ^~~~~~~~~~~~~
                                                         v8::internal::Arguments
/Users/thirstyfish/.node-gyp/0.11.16/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../node-cryptopp.cpp:18:
.././keyring.h:69:51: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
        static v8::Handle<v8::Value> CreateKeyPair(const v8::Arguments& args);
                                                         ^~~~~~~~~~~~~
                                                         v8::internal::Arguments
/Users/thirstyfish/.node-gyp/0.11.16/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../node-cryptopp.cpp:18:
.././keyring.h:70:42: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
        static v8::Handle<v8::Value> Load(const v8::Arguments& args);
                                                ^~~~~~~~~~~~~
                                                v8::internal::Arguments
/Users/thirstyfish/.node-gyp/0.11.16/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../node-cryptopp.cpp:18:
.././keyring.h:71:42: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
        static v8::Handle<v8::Value> Save(const v8::Arguments& args);
                                                ^~~~~~~~~~~~~
                                                v8::internal::Arguments
/Users/thirstyfish/.node-gyp/0.11.16/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../node-cryptopp.cpp:18:
.././keyring.h:72:43: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
        static v8::Handle<v8::Value> Clear(const v8::Arguments& args);
                                                 ^~~~~~~~~~~~~
                                                 v8::internal::Arguments
/Users/thirstyfish/.node-gyp/0.11.16/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../node-cryptopp.cpp:231:31: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
Handle<Value> hexEncode(const Arguments& args){
                              ^~~~~~~~~
                              v8::internal::Arguments
/Users/thirstyfish/.node-gyp/0.11.16/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../node-cryptopp.cpp:232:17: error: calling a protected constructor of class 'v8::HandleScope'
    HandleScope scope;
                ^
/Users/thirstyfish/.node-gyp/0.11.16/deps/v8/include/v8.h:816:13: note: declared protected here
  V8_INLINE HandleScope() {}
            ^
../node-cryptopp.cpp:233:34: error: type 'const v8::internal::Arguments' does not provide a subscript operator
    String::Utf8Value strVal(args[0]->ToString());
                             ~~~~^~
../node-cryptopp.cpp:235:18: error: no member named 'Close' in 'v8::HandleScope'
    return scope.Close(String::New(encoded.c_str()));
           ~~~~~ ^
../node-cryptopp.cpp:235:32: error: no member named 'New' in 'v8::String'
    return scope.Close(String::New(encoded.c_str()));
                       ~~~~~~~~^
../node-cryptopp.cpp:238:31: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
Handle<Value> hexDecode(const Arguments& args){
                              ^~~~~~~~~
                              v8::internal::Arguments
/Users/thirstyfish/.node-gyp/0.11.16/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../node-cryptopp.cpp:239:17: error: calling a protected constructor of class 'v8::HandleScope'
    HandleScope scope;
                ^
/Users/thirstyfish/.node-gyp/0.11.16/deps/v8/include/v8.h:816:13: note: declared protected here
  V8_INLINE HandleScope() {}
            ^
../node-cryptopp.cpp:240:34: error: type 'const v8::internal::Arguments' does not provide a subscript operator
    String::Utf8Value strVal(args[0]->ToString());
                             ~~~~^~
../node-cryptopp.cpp:242:18: error: no member named 'Close' in 'v8::HandleScope'
    return scope.Close(String::New(decoded.c_str()));
           ~~~~~ ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
1 warning and 20 errors generated.
make[1]: *** [Release/obj.target/cryptopp/node-cryptopp.o] Error 1
```
